### ISSUE TITLE
Remove DuplicateElimination from Acknowledgement

### ISSUE THREAD

**Issue by cavycorp** [jentrata/jentrata-msh#62]
In the ebMS 2.0 standard it is not allowed to have a DuplicateElimination indicator in the Acknowledgement message. This change will update the method generateAcknowledgment by removing the lines that will add the DuplicateElimination indicator.

**Comment by aaronwalker** [comment]
No the changes are all good... Is it possible split the changes for #62 and #63 into seperate PRs since now they are all combined in PR #64

**Comment by cavycorp** [comment]
@aaronwalker I don't understand how this happend, I did make the split with #62 and #63 and I see they we're added with #64 and #65 but they are still separate aren't they? I mean #64 only contains the change for #62 and #65 only contains the changes for #63.

**Comment by aaronwalker** [comment]
@cavycorp it's best to make PR from a branch other than master. Basically when you pushed the message Id change to your master branch it get automatically included in any open PR

**Comment by cavycorp** [comment]
@aaronwalker but I made the changes on different forks, so I forked jentrata/jentrata-msh made changes for #62 did the pull-request. Then deleted my repository did another fork of jentrata/jentrata-msh, so without the #62 changes and made the changes for #63 and did the pull request. As far as I can see the changes are separate from each other.

**Comment by cavycorp** [comment]
@aaronwalker, I will close both pull request and will redo them separately from different branches.

**Comment by cavycorp** [comment]
@aaronwalker, I reworked the changes and made two pull requests each from a separate branch from my repository.

**Comment by cavycorp** [comment]
@aaronwalker, do you agree with these changes?

**Comment by cavycorp** [comment]
@aaronwalker can you please accept and merge them into the master of Jentrata-MSH?

**Comment by aaronwalker** [comment]
merged #66 closing
