### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [jentrata/jentrata-msh#68]
Hi
The following lines have cryptographic API misuses. <br> File name => Commons/src/main/java/hk/hku/cecid/piazza/commons/security/KeyStoreComponent.java: Line number => 161: API name => KeyStore:Operation on object of type java.security.KeyStore object not completed. Expected call to load<BR> File name => Commons/src/main/java/hk/hku/cecid/piazza/commons/security/KeyStoreComponent.java: Line number => 155: API name => KeyStore:Operation on object of type java.security.KeyStore object not completed. Expected call to load<BR> File name => Commons/src/main/java/hk/hku/cecid/piazza/commons/security/SMimeMessage.java: Line number => 502: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => Ext/ebxml-pkg/src/main/java/hk/hku/cecid/ebms/pkg/pki/CompositeKeyStore.java: Line number => 226: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => Ext/ebxml-pkg/src/main/java/hk/hku/cecid/ebms/pkg/pki/CompositeKeyStore.java: Line number => 278: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by aaronwalker** [comment]
@mhp0rtal can you please provide details of version your using along with JDK version and JCE provider etc

**Comment by mhp0rtal** [comment]
Hi,
Thanks for your attention.
I reported the cryptographic misuses due to my recent research on how developers employ Java Cryptography Architecture (JCA) APIs in Java applications. I utilized some static analysis tools intended for checking cryptographic practices. The aforementioned misuses in those files were obtained from the results of the tools. The severity of the bug is relative. For instance, Even though MD5 is listed on Java documentation, MD5 is not recommended to use in any language anymore as it is considered insecure. An attacker can try billions of candidate passwords per second on a single GPU. Nevertheless, depending on the scenario the same hash algorithm may not be a problem for file integrity purpose.
There are several instances of cryptographic misuses which could lead to a security vulnerability:
*Do not use ECB mode for encryption.
*Do not use a non-random IV for CBC encryption
*Do not use constant encryption keys.
*Do not use constant salts for PBE.
*Do not use fewer than 1,000 iterations for PBE.
*Do not use static seeds to seed SecureRandom(·)
You can run some static analysis tools on your project (i.e., CryptoLint ) and use the suggestions to make your code more secure.
