### ISSUE TITLE
War file distribution 

### ISSUE THREAD

**Issue by d-lorenc** [jentrata/jentrata-msh#69]
Is it possible to have a war file distribution on jentrata that works for example on tomcat?

I know about existing docker images, but what I would really like, is to have a war file version that I could run on tomcat.

**Comment by aaronwalker** [comment]
@d-lorenc this is basically what maven build produces. Since cloudbees dev@cloud was EOL I haven't migrated the build to another cloud CI tool so you'll need to run the build yourself as per https://github.com/jentrata/jentrata-msh#how-to-build-jentrata-from-source
